# Funding links - displayed on GitHub repository
# These links appear in the "Sponsor" button on GitHub

github: nirholas
# patreon: crypto_data_aggregator
# open_collective: crypto-data-aggregator
# ko_fi: cryptodataaggregator
# custom: ["https://your-crypto-address.eth"]
